# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Demonfort' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Demonfort
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'FirebaseUI/Auth'
  pod 'Firebase/Firestore'
  
  target 'DemonfortTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemonfortUITests' do
    # Pods for testing
  end

end
